steps:
  #### Reservations ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/study-reservation/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/study-reservation/reservations/production',
      ]

  #### Auth ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/study-reservation/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/study-reservation/auth/production',
      ]

  #### Notifications ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/study-reservation/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/study-reservation/notifications/production',
      ]

  #### Payments ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/study-reservation/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/study-reservation/payments/production',
      ]
