steps:
  #### Reservations ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/reservations/production',
      ]

  #### Auth ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/auth/production',
      ]

  #### Notifications ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/notifications/production',
      ]

  #### Payments ####
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/x-plateau-409309/payments/production',
      ]
